- name: Save Netbox Data
  hosts: localhost
  gather_facts: no
  vars:
    api_endpoint: http://0.0.0.0:8000
    token: 4a8d76d62a80e367f32ba3817628bed25198ba0b
  tasks:

    - name: Get netbox devices data
      set_fact:
        devices: "{{ query('netbox.netbox.nb_lookup', 'devices', api_endpoint=api_endpoint, token=token, validate_certs=false) }}"

    - name: Save data to file
      copy:
        content:
          - "{{ devices }}"
        dest: devices.json
